### ISSUE TITLE
EFI Can be mounted from Clover configurator

### ISSUE THREAD

**Issue by ameeno** [evy0311/t440p-hackintosh#1]
I think an easier option is to simply install clover configurator after installing osx, and from clover configurator, you can mount the efi of your usb, and of hard drive,

and simply copy and paste it.

Also you would benefit us by adding hsf to the clover boot pack!

thanks for all your assistance!

**Comment by evy0311** [comment]
Hi! I'm not sure what you mean by mounting it after install. I know you can mount it using Clover Configurator. Also, I will update the guide to already have HFS in the boot pack, but for now it is a step that will have to be done manually when creating the installer.
