### ISSUE TITLE
when is the opencore version available?

### ISSUE THREAD

**Issue by swatchie-1** [evy0311/t440p-hackintosh#10]

**Comment by vmnhat** [comment]
Pm me, i think i can help you

**Comment by evy0311** [comment]
> 
> 
> Pm me, i think i can help you

Unfortunately no way to PM on Github. Mind sending me an email? evan@evanhorsley.com. Im finishing up my OpenCore config and wanted to check stability with you if youd like. Thanks!

**Comment by vmnhat** [comment]
> > Pm me, i think i can help you
> 
> Unfortunately no way to PM on Github. Mind sending me an email? [evan@evanhorsley.com](mailto:evan@evanhorsley.com). Im finishing up my OpenCore config and wanted to check stability with you if youd like. Thanks!

I'd already sent you one time and you delete my comment? so i'll never send you anything more :)
