### ISSUE TITLE
ALC3232.kext has a symlink in it

### ISSUE THREAD

**Issue by null-von-sushi** [evy0311/t440p-hackintosh#2]
I cannot copy `ALC3232.kext` to the USB drive. `ALC3232.kext/Contents/MacOS/AppleHDA` is a symlink it seems, and as far as I understand fat filesystem, it does not support those. Not really sure what to do here.

**Comment by evy0311** [comment]
Thanks for the heads up. I have not had this issue when installing using the files provided from my guide. I will look further into it. You can temporarily search for 'ALC3232.kext' online and download the kext file from elsewhere.

**Comment by null-von-sushi** [comment]
In the interest of reproducibility, I cloned the repo to a XFS filesystem on linux and tried to copy and paste the whole clover folder to the USB.

**Comment by evy0311** [comment]
This issue should be resolved now. I'm not sure why it took the symlink with it when I copied it into my github folder, but it should be resolved. Thanks for pointing this issue out!
