### ISSUE TITLE
Migrate to OpenCore ?

### ISSUE THREAD

**Issue by gitShrekt101** [evy0311/t440p-hackintosh#5]
OpenCore is just so much faster, it'd improve everything if you switched from Clover to OpenCore

**Comment by vmnhat** [comment]
> OpenCore is just so much faster, it'd improve everything if you switched from Clover to OpenCore

I hope someone make EFI for Opencore too

**Comment by vmnhat** [comment]
I just installed successfully from a shared opencore's EFI
Just change something to use imess, facetime
So happy

**Comment by swanux** [comment]
What is your experience with it? Does it worth to switch?

**Comment by vmnhat** [comment]
> What is your experience with it? Does it worth to switch?

I don't see too much different, just wanna try

**Comment by evy0311** [comment]
Hello! Apologies for not replying, GitHub wasn't giving me notifications on issues for some reason.

Anyways, I am planning on moving the guide to using OpenCore here very soon. I am in the process of testing this out and am hoping to upload it here soon! Thanks for the feedback.
