### ISSUE TITLE
is it also working ok for t440p with i5 4200m CPU

### ISSUE THREAD

**Issue by sky-dream** [evy0311/t440p-hackintosh#6]
is it also working ok for t440p with i5 4200m CPU？when i use it on my i5 4200m laptop. it stuck in the logo after the installation APP reboot my laptop.

**Comment by sky-dream** [comment]
t440p with i5 4200m use catalina, found the error AMF :Only 255/256 slide values are usable!, 
checked several T440P EFI on the github, but all comes out the same error when the installation reboot the laptop,

**Comment by swanux** [comment]
For me it works perfectly with Catalina and some tweaks on the EFI side. However it only worked me properly when I've made the USB with Unibeast. If you don't have a real mac for that, but you have a 16GB USB drive, then I can send you the dd image which you can write to USB on any platform.

**Comment by sky-dream** [comment]
ok，tks very much. can you share your img link?
i am not sure it is caused by my different CPU i5 4200m or not,

**Comment by swanux** [comment]
Here it is: https://mega.nz/#!1D5XUSAR!ekme0zWcpUezfCsDcgUer0t1Vaz6nshHRjsfJb425zY
I hope it'll work. Just don't forget that you need to use an exactly 16GB USB drive (not 32 nor 8 and etc)

**Comment by sky-dream** [comment]
ok，tks very much, i will try it with a 10gb usb driver.

**Comment by sky-dream** [comment]
when you finish it, does your t440p support a 4k external monitor?

**Comment by swanux** [comment]
> ok，tks very much, i will try it with a 10gb usb drive

The image itself is more than 10GBs because it's been made from a 16GB drive, so you'll need to use a 16GB one.

**Comment by swanux** [comment]
> when you finish it, does your t440p support a 4k external monitor?

I don't have a 4K monitor, so I don't know. In theory it should.

**Comment by kalido** [comment]
Hi everyone, i'm going to install catalina in a T440p 4300m without GPU using the image that @swanux shared.

**Comment by swanux** [comment]
> Hi everyone, i'm going to install catalina in a T440p 4300m without GPU using the image that @swanux shared. 

Hi, I hope it'll help. Mine is also without a gpu, so it should work.

**Comment by evy0311** [comment]
Hi. Not sure why but GitHub never gave me notifications for your messages here. Apologies. 

I highly recommend against using Unibeast. Vanilla install is always the way to go and it is outlined in my guide how to do so very easily (with some work!). If you are having an issue getting it going using my guide feel free to reach out to me for the exact issues you're having. Myself and many others are running the exact files from my guide without any issue. Id be happy to help you get a vanilla setup going using my guide! :)
