### ISSUE TITLE
Opencore

### ISSUE THREAD

**Issue by ameeno** [evy0311/t440p-hackintosh#7]
Hiya.

I'm trying to get this working on opencore. Can you give me a breakdown of the ssdt so I can debug? Currently I have graphical glitches battery issues and other bugs.

My clover install is working great. Shall I share both efi's with you?

(4712mq, dw1820a, modded bios, ultrabay to internal, non Nvidia)

**Comment by vmnhat** [comment]
Hope t440p opencore release soon!

**Comment by evy0311** [comment]
Hello! Im actually in the process of releasing an OpenCore version of this guide, however I've been caught up with other things going on in my personal life. Im really hoping to release this soon! I have working SSDT's currently and all seems to be working well, im just having a few issues with the dock I'm working to fix. Ill update the guide here once I release it so stay tuned!

**Comment by vmnhat** [comment]
Do you need my Opencore's EFI for t440p?

**Comment by evy0311** [comment]
If you have it, I can take a look at it. I’m in the final stages with mine, and should be releasing soon. I’m in the process of rewriting the guide for it currently. Again, if you have it, I can take a look at it to see if there’s anything I can do different. Also, send over your ACPI stuff so I can see if there is any variances in our two laptops. You can comment a google drive link here or whatever works for you. Thanks!

**Comment by vmnhat** [comment]
https://drive.google.com/drive/folders/1MeknPErwdWki9UBxU9lJPiP4WxtjNzCx

Here you are

**Comment by ameeno** [comment]
@vmhat would you mind sharing it with me too please? i want to iron out my bugs.
