### ISSUE TITLE
Ultra Dock issue

### ISSUE THREAD

**Issue by findyy99** [evy0311/t440p-hackintosh#8]
Hi I have a  T450S,  and I want to get my dock work , but now only the USB ports work, the hdmi and dp are not ok.can you please help me or give some advice and I am using 40A2. Thank you！

**Comment by evy0311** [comment]
Hello! Unfortunately the T450S is different than the T440P and thus, the integrated graphics are different (depending on which CPU you have). This guide is for the T440P, however I'd be happy to assist you. Please post the specs of your machine to help me understand better how to approach this issue.

**Comment by findyy99** [comment]
Hi, very happy to see your replay!
This is the information of my T450S and Ultra dock
    **T450S**
- Intel 5th Generation Architecture (Broadwell)
- Intel HD Graphics 5500
- Realtek ALC3232/ALC292 Audio Codec (alcid=32)
- Intel Series 9 Chipset Family
- macOS Catalina 15.4
- OpenCore Configuration (0.5.7)

**Ultra Dock**
[https://support.lenovo.com/us/en/solutions/pd028010](url)

**Question**
The audio port of the dock does't work. I want to know how to solve this problem. I wish you could give me some guide. Thank you again!

**Comment by findyy99** [comment]
> Hello! Unfortunately the T450S is different than the T440P and thus, the integrated graphics are different (depending on which CPU you have). This guide is for the T440P, however I'd be happy to assist you. Please post the specs of your machine to help me understand better how to approach this issue.

Hi, I read the AppleAlC's Github, found that there have a layout-id 55 for my ALC292, so the docking station audio works now. But it is not very perfect, the audio icon of macOS will be loaded after about 1min, when i adjust the volume, the button seems a little floating, not very comfortable. Do you have this issue? Anyway, Thank you for your replay!

**Comment by swatchie-1** [comment]
Thanks alot Jianzhao, the audio in dock works okay. Only issue now for T440P is the reboot when laptop goes to sleep while in dock. Does yours reboot when you sleep the laptop while docking?

**Comment by findyy99** [comment]
> Thanks alot Jianzhao, the audio in dock works okay. Only issue now for T440P is the reboot when laptop goes to sleep while in dock. Does yours reboot when you sleep the laptop while docking?

No thanks! I am using dock 40A2, my T450s haven't show the issue you said. I think you should try update the T440P bios or the dock's bios. If you need, I would like to share my OpenCore EFI folder to you!

**Comment by swatchie-1** [comment]
Hi @jianzhao0806 thanks would try it out on my t440p to see if it works. Do you want to create a repo for us to access or email me?

**Comment by findyy99** [comment]
> Hi @jianzhao0806 thanks would try it out on my t440p to see if it works. Do you want to create a repo for us to access or email me?

this is the EFI, you may need do some changes. [OpenCore-058](https://drive.google.com/open?id=1xJw_Sg742W-V2bcqwuG3A7J7vksCJeiD)

**Comment by swatchie-1** [comment]
@jianzhao0806 Hi tried it but it can't boot my t440p when i used it with a USB drive

**Comment by findyy99** [comment]
> @jianzhao0806 Hi tried it but it can't boot my t440p when i used it with a USB drive

Of course, you need make some changes, my graphic is hd5500, dual battery, you should change config depends on your hardware.

**Comment by swatchie-1** [comment]
@evy0311 Still waiting for your opencore version.

**Comment by swatchie-1** [comment]
@evy0311 want to work on this OpenCore for t4c0p together?

**Comment by swatchie-1** [comment]
Hello @jianzhao0806 i'm testing OC now for my T440P. Can you confirm your T450 does not reboot when you shut down the laptop while using the Dock's external display output?

**Comment by findyy99** [comment]
@swatchie-1 I am sure ! My dock works fine. I test the HDMI, headphone interface, USB, All works fine.

**Comment by Potreba** [comment]
Hi! I use i7-4810mq integrated graphicss and have problems with going to sleep in ultradock. In fact I cannot turn off too , only restart. Another bad issue is working with external hard drives. Under windows they work fine, but under macos I can reliably work only with usb drives. Another issue is if I put computer with lid down and open it after docked it might reboot (not sure if its 100% repeatable)

Btw VGA and DVi outputs are doubling

**Comment by swanux** [comment]
Same for me as @Potreba, with the exception of external drive problems and lid opening restart.

**Comment by Potreba** [comment]
@swanux same with the lid opening. External drives too, but if I use single disk with usb3 enclosure and exFAT filesystem it's ok

**Comment by swanux** [comment]
@swatchie-1 I've put together an OpenCore configuration from several resources (still in early stages). Currently I have the same dock reboot issue which you've mentioned above. Maybe we could compare OC configs to get the best results. If you're interested, you can access mine [here](https://github.com/swanux/t440p).

**Comment by swatchie-1** [comment]
@swanux everything else working well for you? sound, wifi, etc.

**Comment by swanux** [comment]
@swatchie-1 it's described in the Readme. Anyway, there is no way for working wifi with default card. Sound and others are fine except some minor problems.

**Comment by swatchie-1** [comment]
@swanux nice work. Which wifi card are you using? I'm using the DW1820A. 
The Personal Hotspot via wifi doesn't work on my own phone. Also the Apple Watch Unlock doesn't work. I wonder if it works on yours. Other functions for the wifi works well.

Yes the dock kernel panic needs a fix. Any suggestion on which direction to go to solve this?

**Comment by findyy99** [comment]
fortunately, my T450S with Dock 40A2 HDMI, audio, USB works fine.

**Comment by swatchie-1** [comment]
@findyy99 good for you. Maybe swanux can solve it for us.

**Comment by findyy99** [comment]
@swatchie-1 wish you good luck. And Big Sur was already released!😄😄😄

**Comment by swanux** [comment]
@swatchie-1 thanks! I'm currently using a TP-Link adapter, but already purchased some cheap stuff from ebay, I'll use original apple Airport card. I don't have any apple product (never had), so I can't confirm those functions that you've mentioned, but I guess with the airport card it should work.

**Comment by swatchie-1** [comment]
@swanux i hope you have got your adapters ready too. Seemed quite tight for airport card to fit in there.

**Comment by swanux** [comment]
@findyy99 regarding big sur, I recommend you to install deepin Linux 20 instead. They look the same, but with deepin everything will work. There's no other difference as big sur is a shame from apple (R.I.P Steve Jobs). Anyway, when the final release comes out, probably I'll add support for it too.

**Comment by swanux** [comment]
@swatchie-1 yeah, I know. I've linked a guide in the Readme that I'll follow myself too.

**Comment by swatchie-1** [comment]
@swanux i also recommend you get an additional heat pipe for your processor such as this [guy here](https://www.reddit.com/r/thinkpad/comments/cwi4vz/a_dual_heatpipe_heatsink_for_the_igp_t440p/).

Cools your laptop by 10 degrees during high usage.

**Comment by swanux** [comment]
@swatchie-1 Really impressive! Currently I have no issues with temperature, but I plan a CPU upgrade, so I'll bookmark it for later.

**Comment by swatchie-1** [comment]
@swanux okay. hope you can find a solution for the ultra dock sleep KP soon. it will be a great help for the t440p community :)

**Comment by swanux** [comment]
@swatchie-1 yeah I hope it too. Currently I have no idea where to start, but if I find anything I'll update the repo. If you have anything in mind, please let me know.
